version: '3.7'

services:
  cron:
    build: docker/cron
    restart: unless-stopped
    volumes:
      - ./appConfig/cron/1min:/etc/periodic/1min:ro
      - ./appConfig/cron/15min:/etc/periodic/15min:ro
      - ./appConfig/cron/hourly:/etc/periodic/hourly:ro
      - ./appConfig/cron/daily:/etc/periodic/daily:ro
      - ./appConfig/cron/weekly:/etc/periodic/weekly:ro
      - ./appConfig/cron/monthly:/etc/periodic/monthly:ro
      # access docker containers outside this container
      - /var/run/docker.sock:/var/run/docker.sock
    command: crond -f -l 8